name: aaa1

on:
  push:
    branches:
      - main
    
  workflow_dispatch:
  
jobs:

  call-workflow1:
    concurrency:
      group: AAA
      cancel-in-progress: false
  
    -
      run: |
        echo ${{ github.ref }}
