name: aaa1

on:
  push:
    branches:
      - main
    
  workflow_dispatch:
  
jobs:

  aaajob1_1:
    runs-on: ubuntu-latest
    
    steps:
      -
        run: |
          echo "xxxxxxxxx"

  aaajob1_2:
    runs-on: ubuntu-latest
    
    concurrency:
      group: AAA
      cancel-in-progress: true
    
    steps:
      -
        run: |
          sleep 10
          echo ${{ github.ref }}
