name: aaa1

on:
  push:
    branches:
      - main
    
  workflow_dispatch:
  
jobs:

  job1:
    runs-on: ubuntu-latest
    
    concurrency:
      group: AAA
      cancel-in-progress: false
  
    -
      run: |
        echo ${{ github.ref }}
