name: aaa1

on:
  push:
    branches:
      - main
    
  workflow_dispatch:

concurrency:
  group: AAA
  cancel-in-progress: false
  
jobs:

  call-workflow1:
    uses: ./.github/workflows/wfc1.yml

  call-workflow2:
    uses: ./.github/workflows/wfc2.yml
