name: aaa1

on:
  push:
    branches:
      - main
    
  workflow_dispatch:
  
jobs:

  aaajob1:
    runs-on: ubuntu-latest
    
    concurrency:
      group: AAA
      cancel-in-progress: false
    
    steps:
      -
        run: |
          sleep 5
          echo ${{ github.ref }}
