name: aaa2

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs:

  call-workflow2:
    concurrency:
      group: AAA
      cancel-in-progress: false
  
    -
      run: |
        echo ${{ github.ref }}
