name: aaa2

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs:

  job2:
    runs-on: ubuntu-latest

    concurrency:
      group: AAA
      cancel-in-progress: false
  
    -
      run: |
        echo ${{ github.ref }}
