name: aaa2

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs:

  aaajob2:
    runs-on: ubuntu-latest

    concurrency:
      group: AAA
      cancel-in-progress: true
  
    steps:
      -
        run: |
          sleep 10
          echo ${{ github.ref }}
