name: aaa3

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs:

  aaajob3_1:
    runs-on: ubuntu-latest
    
    steps:
      -
        run: |
          echo "xxxxxxxxx
          
  aaajob3_2:
    runs-on: ubuntu-latest

    concurrency:
      group: AAA
      cancel-in-progress: true
  
    steps:
      -
        run: |
          sleep 10
          echo ${{ github.ref }}
